### ISSUE TITLE
CMake Error: Error required internal CMake variable not set, cmake may not be built correctly. Missing variable is: CMAKE_C_COMPILE_OBJEC

### ISSUE THREAD

**Issue by AlexLuya** [arangodb/fuerte#18] opened 2019-05-01 13:05 UTC
Hello,my configuration like this:
   ubuntu------------18.04
   gcc-----------------7.3.0
   fuerte--------------72b0ccd 0c2304c
   cmake-------------3.14.3

`cmake ..  -DCMAKE_BUILD_TYPE=Debug -DFUERTE_TESTS=ON -DFUERTE_EXAMPLES=ON -DVELOCYPACK_SOURCE_DIR=../..//velocypack/`

gives error:
-- The CXX compiler identification is GNU 7.3.0
-- Check for working CXX compiler: /usr/lib/ccache/c++
-- Check for working CXX compiler: /usr/lib/ccache/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.1.0g")  
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Boost version: 1.68.0
-- Found the following Boost libraries:
--   system
--   thread
--   chrono
--   date_time
--   atomic
-- The C compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Build mode: Debug
-- Install base directory: /usr/local
CMake Warning (dev) at /home/../velocypack/CMakeLists.txt:24 (set):
  implicitly converting 'path' to 'STRING' type.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Hardware support for SSE4.2 on this machine: true
-- Compiler type GNU: /usr/lib/ccache/c++
-- Building with SSE 4.2 optimizations enabled: ON
-- Building with hash type: xxhash
-- Building bench performance test suite: OFF
-- Building support programs and tools: ON
-- Building examples: OFF
-- Building test suite: OFF
-- Building large tests: OFF
-- Building assembler test suite: OFF
-- Compiler type UNKNOWN: /usr/lib/ccache/c++
-- Enabling Fuerte checked mode: -DFUERTE_CHECKED_MODE
-- Found PythonInterp: /usr/bin/python (found version "3.6.7") 
-- Configuring done
CMake Error: Error required internal CMake variable not set, cmake may not be built correctly.
Missing variable is:
CMAKE_C_COMPILE_OBJECT
-- Generating done

How to fix this bug?

**Comment by sptrakesh** [comment] 2019-05-19 16:59
Looks like that particular error is coming from the test suite (or maybe example).  I turned both off (the default), and that particular error does not occur.

Also for some reason the http_parser does not get compiled without adding the following file to the main cmake file:

```set_source_files_properties(src/http_parser/http_parser.c PROPERTIES LANGUAGE CXX)```

I was able to use the `fuerte-get` test tool to connect to the official docker container running locally.

**Comment by ObiWahn** [comment] 2019-05-20 09:37
Hi, could you try to build fuerte again. The project was missing the C language. Therefore the .c source was ignored. I have changed it to `project(fuerte CXX C)`.

**Comment by ObiWahn** [comment] 2019-05-20 09:38
https://github.com/arangodb/fuerte/issues/13 is a duplicate of this bug

**Comment by sptrakesh** [comment] 2019-05-20 14:34
Compiles without issues now on my end.

**Comment by ObiWahn** [comment] 2019-05-21 14:51
Nice! Thank you for the confirmation!

**Closed as completed by ObiWahn** 2019-05-21 14:51 UTC
